# Reusable workflow for building binaries

name: Binaries

on:
  workflow_call:
    inputs:
      linux_builder_repo_and_digest:
        # Use .github/find-container-digest action to get this
        description: |
          Docker repo and image digest of the Linux builder container, or
          empty to skip Linux build
        required: false
        type: string
      macos_enable:
        description: Build macOS binaries
        required: false
        type: boolean
        default: false
      openslide_repo:
        description: Override OpenSlide with this repo
        required: false
        type: string
      openslide_ref:
        description: Override OpenSlide with this openslide_repo ref
        required: false
        type: string
      openslide_java_repo:
        description: Override OpenSlide Java with this repo
        required: false
        type: string
      openslide_java_ref:
        description: Override OpenSlide Java with this openslide_java_repo ref
        required: false
        type: string
      openslide_bin_repo:
        description: Use openslide-bin from this repo
        required: false
        type: string
        default: openslide/openslide-bin
      openslide_bin_ref:
        description: Use openslide-bin from this ref
        required: false
        type: string
        default: main
      suffix:
        description: Set package version suffix
        required: true
        type: string
      werror:
        description: Fail on build warnings in OpenSlide packages
        required: false
        type: boolean
        default: false
      windows_builder_repo_and_digest:
        # Use .github/find-container-digest action to get this
        description: |
          Docker repo and image digest of the Windows builder container
        required: true
        type: string
    outputs:
      version:
        description: The version of the output artifacts
        value: ${{ jobs.sdist.outputs.version }}

permissions:
  contents: read

jobs:
  sdist:
    name: Source tarball
    runs-on: ubuntu-latest
    container: ${{ inputs.windows_builder_repo_and_digest }}
    outputs:
      artifact_base: ${{ steps.prep.outputs.artifact_base }}
      artifact: ${{ steps.prep.outputs.artifact }}
      version: ${{ steps.prep.outputs.version }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.openslide_bin_repo }}
          ref: ${{ inputs.openslide_bin_ref }}

      - name: Check out OpenSlide
        if: inputs.openslide_repo != ''
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.openslide_repo }}
          ref: ${{ inputs.openslide_ref }}
          # make sure "git describe" works
          fetch-depth: 0
          path: override/openslide
          persist-credentials: false
      - name: Check out OpenSlide Java
        if: inputs.openslide_java_repo != ''
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.openslide_java_repo }}
          ref: ${{ inputs.openslide_java_ref }}
          # make sure "git describe" works
          fetch-depth: 0
          path: override/openslide_java
          persist-credentials: false
      - name: Collect overrides
        if: inputs.openslide_repo != '' || inputs.openslide_java_repo != ''
        run: tar cf overrides.tar override
      - name: Upload overrides
        if: inputs.openslide_repo != '' || inputs.openslide_java_repo != ''
        uses: actions/upload-artifact@v4
        with:
          name: build-overrides
          path: overrides.tar

      - name: Cache sources
        uses: actions/cache@v3
        with:
          key: build-packagecache
          path: subprojects/packagecache
      - name: Build source tarball
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ./build.sh -x "${{ inputs.suffix }}" sdist
      - name: Prep artifact
        id: prep
        run: |
          version=$(./build.sh -x "${{ inputs.suffix }}" version)
          echo "version=$version" >> $GITHUB_OUTPUT
          artifact_base="openslide-bin-${version}"
          echo "artifact_base=$artifact_base" >> $GITHUB_OUTPUT
          echo "artifact=${artifact_base}.tar.gz" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prep.outputs.artifact }}
          path: ${{ steps.prep.outputs.artifact }}
          compression-level: 0

  windows:
    name: Windows
    needs: sdist
    runs-on: ubuntu-latest
    container: ${{ inputs.windows_builder_repo_and_digest }}
    outputs:
      artifact_base: ${{ steps.build.outputs.artifact_base }}
      artifact: ${{ steps.build.outputs.artifact }}
    steps:
      - name: Download source tarball
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.sdist.outputs.artifact }}
      - name: Unpack source tarball
        run: |
          tar xf "${{ needs.sdist.outputs.artifact }}"
          mv "${{ needs.sdist.outputs.artifact_base }}"/* .
          rm -r "${{ needs.sdist.outputs.artifact_base }}" \
              "${{ needs.sdist.outputs.artifact }}"
      - name: Download overrides
        if: inputs.openslide_repo != '' || inputs.openslide_java_repo != ''
        uses: actions/download-artifact@v4
        with:
          name: build-overrides
      - name: Unpack overrides
        if: inputs.openslide_repo != '' || inputs.openslide_java_repo != ''
        run: tar xf overrides.tar && rm overrides.tar
      - name: Build binary zip
        id: build
        run: |
          werror=
          if [ "${{ inputs.werror }}" = true ]; then
              werror="-w"
          fi
          ./build.sh -x "${{ inputs.suffix }}" $werror bdist
          artifact_base="openslide-bin-${{ needs.sdist.outputs.version }}-windows-x64"
          echo "artifact_base=$artifact_base" >> $GITHUB_OUTPUT
          echo "artifact=${artifact_base}.zip" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact }}
          path: ${{ steps.build.outputs.artifact }}
          compression-level: 0

  windows-smoke:
    name: Windows smoke test
    needs: [sdist, windows]
    runs-on: windows-latest
    steps:
      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.windows.outputs.artifact }}
      - name: Unpack Windows build
        shell: bash
        run: unzip "${{ needs.windows.outputs.artifact }}"
      - name: Report package versions
        shell: bash
        run: cat "${{ needs.windows.outputs.artifact_base }}/VERSIONS.md" >> $GITHUB_STEP_SUMMARY
      - name: Smoke test
        shell: bash
        run: |
          cd "${GITHUB_WORKSPACE}/${{ needs.windows.outputs.artifact_base }}/bin"
          OPENSLIDE_DEBUG=synthetic ./slidetool.exe prop list ""
