# Temporary workflow to build Linux and macOS binaries directly with Meson

name: Direct

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container: ghcr.io/openslide/linux-builder:latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Cache sources
        uses: actions/cache@v3
        with:
          key: direct-cache
          path: subprojects/packagecache
      - name: Build
        run: |
          meson setup build --native-file machines/native-linux-x86_64.ini \
              -Dopenslide_werror=true
          meson compile -C build
          mkdir output
          cp build/artifacts/openslide-bin-linux*.xz output/
      - name: Smoke test
        run: |
          tar xf output/*.xz
          OPENSLIDE_DEBUG=synthetic \
              openslide-bin-linux-*/bin/slidetool prop list ''
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: output
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install meson
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Cache sources
        uses: actions/cache@v3
        with:
          key: direct-cache
          path: subprojects/packagecache
      - name: Build
        run: |
          export OPENSLIDE_BIN_VERSION=$(MESON_SOURCE_ROOT=$(pwd) python3 artifacts/get-version.py)
          for arch in x86_64 arm64; do
              meson setup $arch --cross-file machines/cross-macos-${arch}.ini \
                  -Dopenslide_werror=true
              meson compile -C $arch
          done
          mkdir output
          python3 artifacts/write-universal-bdist.py \
              -o output/openslide-bin-macos-arm64-x86_64-${OPENSLIDE_BIN_VERSION}.tar.xz \
              */artifacts/openslide-bin-macos-*.tar.xz
      - name: Smoke test
        run: |
          tar xf output/*.xz
          OPENSLIDE_DEBUG=synthetic \
              openslide-bin-macos-*/bin/slidetool prop list ''
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: output
