# Privileged workflow to label issues and PRs for dependency updates

name: Events

on:
  issues:
    types: [opened, closed]
  pull_request_target:
    branches: [main]
    types: [opened]

permissions:
  issues: write
  pull-requests: write

env:
  GH_LABEL: update

jobs:
  process-event:
    name: Process
    runs-on: ubuntu-latest
    outputs:
      bot-user: ${{ steps.bot-user.outputs.username }}
    steps:
      - name: Get bot username
        id: bot-user
        env:
          GITHUB_TOKEN: ${{ secrets.OPENSLIDE_BOT_TOKEN }}
        run: echo "username=$(gh api user -q .login)" >> $GITHUB_OUTPUT
      - name: Label dependency issue
        if: >-
          github.event_name == 'issues' &&
          github.event.action == 'opened' &&
          github.actor == steps.bot-user.outputs.username &&
          contains(github.event.issue.body, 'topic=dependencies')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit -R "${{ github.repository }}" \
              "${{ github.event.issue.number }}" \
              --add-label $GH_LABEL
      - name: Label dependency PR
        if: >-
          github.event_name == 'pull_request_target' &&
          github.actor == steps.bot-user.outputs.username &&
          contains(github.event.pull_request.body, 'topic=dependencies')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit -R "${{ github.repository }}" \
              "${{ github.event.number }}" \
              --add-label $GH_LABEL
  update-from-event:
    name: Check for updates
    needs: process-event
    if: >-
      github.event_name == 'issues' &&
      github.event.action == 'closed' &&
      github.event.issue.user.login == needs.process-event.outputs.bot-user &&
      contains(github.event.issue.body, 'topic=dependencies')
    uses: ./.github/workflows/update-check.yml
