# Automatically create a release when tagged

name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

concurrency: release-${{ github.ref }}

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    outputs:
      linux_builder_repo_and_digest: ${{ steps.find-linux.outputs.builder_repo_and_digest }}
      windows_builder_repo_and_digest: ${{ steps.find-windows.outputs.builder_repo_and_digest }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Find Linux builder container digest
        id: find-linux
        uses: ./.github/find-container-digest
        with:
          builder_image: linux
      - name: Find Windows builder container digest
        id: find-windows
        uses: ./.github/find-container-digest
        with:
          builder_image: windows

  stable:
    name: Stable
    needs: setup
    uses: ./.github/workflows/build.yml
    with:
      linux_builder_repo_and_digest: ${{ needs.setup.outputs.linux_builder_repo_and_digest }}
      macos_enable: true
      openslide_bin_repo: ${{ github.repository }}
      openslide_bin_ref: ${{ github.ref }}
      suffix: ""
      windows_builder_repo_and_digest: ${{ needs.setup.outputs.windows_builder_repo_and_digest }}

  release:
    name: Release
    needs: [setup, stable]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.stable.outputs.artifact }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          unzip "${{ needs.stable.outputs.artifact }}/openslide-bin-${{ needs.stable.outputs.version }}-windows-x64.zip"

          echo "## Changes" > changes
          awk -e '/^## / && ok {exit}' \
              -e '/^## / {ok=1; next}' \
              -e 'ok {print}' \
              "openslide-win64-${{ needs.setup.outputs.pkgver }}/CHANGELOG.md" \
              >> changes
          echo -e "## Versions\n" >> changes
          cat "openslide-bin-${{ needs.stable.outputs.version }}-windows-x64/VERSIONS.md" \
              >> changes

          gh release create --latest --verify-tag \
              --repo "${{ github.repository }}" \
              --title "openslide-bin ${{ needs.stable.outputs.version }}" \
              --notes-file changes \
              "${{ github.ref_name }}" \
              "${{ needs.stable.outputs.artifact }}/"*
