# Privileged workflow to label issues and PRs with dependency updates

name: Updates - label

on:
  issues:
    types: [opened]
  pull_request_target:
    branches: [main]
    types: [opened]

permissions:
  issues: write
  pull-requests: write

env:
  GH_LABEL: update

jobs:
  label-update:
    name: Label update
    runs-on: ubuntu-latest
    steps:
      - name: Get bot username
        id: user
        env:
          GITHUB_TOKEN: ${{ secrets.OPENSLIDE_BOT_TOKEN }}
        run: echo "username=$(gh api user -q .login)" >> $GITHUB_OUTPUT
      - name: Add label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.actor }}" != "${{ steps.user.outputs.username }}" ]
          then
              echo "Author isn't bot; exiting"
              exit 0
          fi
          case "${{ github.event_name }}" in
          issues)
              found=${{ contains(github.event.issue.body, 'topic=dependencies') }}
              if [ "$found" = true ]; then
                  gh issue edit -R "${{ github.repository }}" \
                      "${{ github.event.issue.number }}" \
                      --add-label $GH_LABEL
              fi
              ;;
          pull_request_target)
              found=${{ contains(github.event.pull_request.body, 'topic=dependencies') }}
              if [ "$found" = true ]; then
                  gh pr edit -R "${{ github.repository }}" \
                      "${{ github.event.number }}" \
                      --add-label $GH_LABEL
              fi
              ;;
          *)
              echo "Unknown event: ${{ github.event_name }}"
              exit 1
          esac
